name: Publish PublicAPI to IIS 🚀

on: 
  workflow_dispatch:
  push:
      branches:
        - main

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    # dotnet build and publish
    
    - name: Build CarSharingApp PublicAPI
      run: dotnet build --configuration Release ./CarSharingApp.PublicApi

    - name: Publish CarSharingApp PublicAPI to Azure VM 
      run: |
        dotnet publish -c Release -o dotnetcorecarsharingapppublicapi ./CarSharingApp.PublicApi
        
    - name: Build CarSharingApp Web
      run: |
        dotnet build --configuration Release ./CarSharingApp.Web

    - name: Publish CarSharingApp Web to Azure VM 
      run: |
        dotnet publish -c Release -o dotnetcorecarsharingappweb ./CarSharingApp.Web
        
    - name: Deploy PublicAPI and Web to IIS
      run: |
        iisreset /stop
        Copy-Item ./dotnetcorecarsharingapppublicapi/* C:/Car" "Sharing" "App" "Public" "Api -Recurse -Force
        Copy-Item ./dotnetcorecarsharingappweb/* C:/Car" "Sharing" "App" "Web -Recurse -Force
        iisreset /start
    
    - name: Curl PublicAPI as a smoke test
      run: curl https://carsharingapp.norwayeast.cloudapp.azure.com:21001/swagger

    - name: Curl Web application as a smoke test
      run: curl https://carsharingapp.norwayeast.cloudapp.azure.com:21002
